# -*- coding: utf-8 -*-
"""리뷰 결과 JSON들을 종합하여 output/stock-analyzer_full_review.txt를 생성한다."""

import json
import os

BATCHES = [
    ("review_result.json", "Batch 1: Core (api_client, orchestrator, database, cache, analysis router)"),
    ("review_batch2a.json", "Batch 2a: Agents (analyst, claude_client, cross_validation, compare)"),
    ("review_batch2b.json", "Batch 2b: Agents (news, data, macro, sector_analyzer)"),
    ("review_batch3.json", "Batch 3: Backend Routers (main, quote, sector, compare, market, watchlist, search, alerts, guide)"),
    ("review_batch4a.json", "Batch 4a: Data Clients (finnhub, finviz, fmp, fred)"),
    ("review_batch4b.json", "Batch 4b: Data Clients (twelvedata, yfinance, watchlist, alerts)"),
]

os.makedirs("output", exist_ok=True)

all_data = []
for fname, desc in BATCHES:
    with open(fname, "r", encoding="utf-8") as f:
        data = json.load(f)
    all_data.append((desc, data))

with open("output/stock-analyzer_full_review.txt", "w", encoding="utf-8") as out:
    out.write("=" * 80 + "\n")
    out.write("  STOCK-ANALYZER 전체 코드 리뷰 보고서\n")
    out.write("  Generated by: Code Review Pipeline (4-Agent System)\n")
    out.write("  Date: 2026-04-21\n")
    out.write("  Target: https://github.com/SoyeonAhn3/stock-analyzer.git\n")
    out.write("=" * 80 + "\n\n")

    # --- 1. 종합 요약 ---
    out.write("━" * 80 + "\n")
    out.write("  1. 종합 요약 (Executive Summary)\n")
    out.write("━" * 80 + "\n\n")

    total_c, total_w, total_i = 0, 0, 0
    batch_scores = []
    for desc, data in all_data:
        s = data.get("findings", {}).get("summary", {})
        score = s.get("overall_score", 0)
        grade = s.get("grade", "N/A")
        t = s.get("total_issues", {})
        total_c += t.get("critical", 0)
        total_w += t.get("warning", 0)
        total_i += t.get("info", 0)
        batch_scores.append((desc, score, grade, t))

    total_all = total_c + total_w + total_i
    avg_score = sum(s for _, s, _, _ in batch_scores) / len(batch_scores)

    out.write(f"  평균 점수: {avg_score:.0f}/100\n")
    out.write(f"  총 발견 이슈: {total_all}건\n")
    out.write(f"    - Critical: {total_c}건\n")
    out.write(f"    - Warning:  {total_w}건\n")
    out.write(f"    - Info:     {total_i}건\n\n")

    out.write("  분석 대상 파일 (6개 배치, 총 ~4,500줄):\n")
    out.write("    - Core: api_client.py, orchestrator.py, database.py, cache.py, analysis.py\n")
    out.write("    - Agents: analyst, claude_client, cross_validation, compare, news, data, macro, sector\n")
    out.write("    - Backend: main.py + 8개 라우터\n")
    out.write("    - Data Clients: finnhub, finviz, fmp, fred, twelvedata, yfinance, watchlist, alerts\n\n")

    out.write("  배치별 점수:\n")
    out.write("  " + "-" * 76 + "\n")
    out.write(f"  {'배치':<55} {'점수':>8} {'등급':>6}\n")
    out.write("  " + "-" * 76 + "\n")
    for desc, score, grade, t in batch_scores:
        out.write(f"  {desc:<55} {score:>5}/100  {grade:>4}\n")
    out.write("  " + "-" * 76 + "\n\n")

    # --- 2. 배치별 상세 분석 결과 ---
    out.write("\n" + "━" * 80 + "\n")
    out.write("  2. 배치별 상세 분석 결과\n")
    out.write("━" * 80 + "\n")

    for idx, (desc, data) in enumerate(all_data, 1):
        findings = data.get("findings", {})
        summary = findings.get("summary", {})

        out.write(f"\n{'─' * 80}\n")
        out.write(f"  2.{idx} {desc}\n")
        out.write(f"      점수: {summary.get('overall_score', 'N/A')}/100 | 등급: {summary.get('grade', 'N/A')}\n")
        t = summary.get("total_issues", {})
        out.write(f"      이슈: Critical {t.get('critical', 0)} | Warning {t.get('warning', 0)} | Info {t.get('info', 0)}\n")
        out.write(f"{'─' * 80}\n\n")

        # Security
        sec = findings.get("security", {})
        sec_issues = sec.get("issues", [])
        if sec_issues:
            out.write("  [Security Agent 분석 결과]\n\n")
            for i, issue in enumerate(sec_issues, 1):
                out.write(f"    #{i} [{issue.get('severity', '?').upper()}] (confidence: {issue.get('confidence', '?')})\n")
                out.write(f"    Line: {issue.get('line', '?')}\n")
                out.write(f"    이슈: {issue.get('issue', '')}\n")
                snippet = issue.get("code_snippet", "")
                if snippet:
                    snippet_display = snippet[:120].replace("\n", " | ")
                    out.write(f"    코드: {snippet_display}\n")
                suggestion = issue.get("suggestion", "")
                if suggestion:
                    out.write("    제안:\n")
                    for line in suggestion.split("\n"):
                        out.write(f"      {line}\n")
                out.write("\n")

            sec_summary = sec.get("summary", "")
            if sec_summary:
                out.write("    [Security 요약]\n")
                for line in sec_summary.split("\n"):
                    out.write(f"    {line}\n")
                out.write("\n")

        # Performance
        perf = findings.get("performance", {})
        perf_issues = perf.get("issues", [])
        if perf_issues:
            out.write("  [Performance Agent 분석 결과]\n\n")
            for i, issue in enumerate(perf_issues, 1):
                out.write(f"    #{i} [{issue.get('severity', '?').upper()}] (confidence: {issue.get('confidence', '?')})\n")
                out.write(f"    Line: {issue.get('line', '?')}\n")
                out.write(f"    이슈: {issue.get('issue', '')}\n")
                snippet = issue.get("code_snippet", "")
                if snippet:
                    snippet_display = snippet[:120].replace("\n", " | ")
                    out.write(f"    코드: {snippet_display}\n")
                suggestion = issue.get("suggestion", "")
                if suggestion:
                    out.write("    제안:\n")
                    for line in suggestion.split("\n"):
                        out.write(f"      {line}\n")
                out.write("\n")

        # Quality
        qual = findings.get("quality", {})
        qual_issues = qual.get("issues", [])
        if qual_issues:
            out.write("  [Quality Agent 분석 결과]\n\n")
            for i, issue in enumerate(qual_issues, 1):
                out.write(f"    #{i} [{issue.get('severity', '?').upper()}] (confidence: {issue.get('confidence', '?')})\n")
                out.write(f"    Line: {issue.get('line', '?')}\n")
                out.write(f"    이슈: {issue.get('issue', '')}\n")
                suggestion = issue.get("suggestion", "")
                if suggestion:
                    out.write("    제안:\n")
                    for line in suggestion.split("\n"):
                        out.write(f"      {line}\n")
                out.write("\n")

    # --- 3. Critical 이슈 통합 ---
    out.write("\n" + "━" * 80 + "\n")
    out.write("  3. Critical 이슈 통합 목록 (즉시 수정 필요)\n")
    out.write("━" * 80 + "\n\n")

    critical_num = 0
    for desc, data in all_data:
        issues = data.get("findings", {}).get("summary", {}).get("all_issues", [])
        for issue in issues:
            if issue.get("severity") == "critical":
                critical_num += 1
                out.write(f"  [{critical_num}] {issue.get('issue', '')}\n")
                out.write(f"      Agent: {issue.get('agent', '?')} | Line: {issue.get('line', '?')}\n")
                out.write(f"      Batch: {desc}\n")
                suggestion = issue.get("suggestion", "")
                first_line = suggestion.split("\n")[0] if suggestion else ""
                out.write(f"      제안: {first_line}\n\n")

    # --- 4. Warning 이슈 통합 ---
    out.write("\n" + "━" * 80 + "\n")
    out.write("  4. Warning 이슈 통합 목록 (개선 권장)\n")
    out.write("━" * 80 + "\n\n")

    warn_num = 0
    for desc, data in all_data:
        issues = data.get("findings", {}).get("summary", {}).get("all_issues", [])
        for issue in issues:
            if issue.get("severity") == "warning":
                warn_num += 1
                out.write(f"  [{warn_num}] {issue.get('issue', '')}\n")
                out.write(f"      Agent: {issue.get('agent', '?')} | Line: {issue.get('line', '?')}\n")
                out.write(f"      Batch: {desc}\n")
                suggestion = issue.get("suggestion", "")
                first_line = suggestion.split("\n")[0] if suggestion else ""
                out.write(f"      제안: {first_line}\n\n")

    # --- 5. 개선 로드맵 ---
    out.write("\n" + "━" * 80 + "\n")
    out.write("  5. 개선 로드맵 제안\n")
    out.write("━" * 80 + "\n\n")

    out.write("  [단기 - 1주 이내]\n")
    out.write("    1. 모든 API 엔드포인트에 입력값 검증(정규식 화이트리스트) 추가\n")
    out.write("    2. 인증/인가 미들웨어 + Rate Limiting 적용\n")
    out.write("    3. 로그 인젝션 방지 (sanitize 함수 적용)\n")
    out.write("    4. 에러 응답에서 내부 정보 제거\n")
    out.write("    5. API 키 하드코딩/노출 점검 및 환경 변수 분리\n\n")

    out.write("  [중기 - 1개월 이내]\n")
    out.write("    1. 외부 API 호출 병렬화 (ThreadPoolExecutor / asyncio.gather)\n")
    out.write("    2. 메모리 캐시 LRU 정책 + 만료 항목 정리 로직 추가\n")
    out.write("    3. Agent 코드 중복 제거 (BaseAgent 추상 클래스)\n")
    out.write("    4. 타입 힌팅 강화 + Enum 도입\n")
    out.write("    5. CI/CD 파이프라인 구축 (GitHub Actions)\n")
    out.write("    6. DB 연결 관리 개선 (컨텍스트 매니저, 커넥션 풀링)\n\n")

    out.write("  [장기 - 분기 이내]\n")
    out.write("    1. SQLite -> PostgreSQL 마이그레이션 (멀티 인스턴스 대비)\n")
    out.write("    2. E2E 테스트 도입 (Playwright)\n")
    out.write("    3. 모니터링 + 알림 체계 (Sentry, Prometheus)\n")
    out.write("    4. API 응답 스키마 표준화 (Pydantic Response Model)\n")
    out.write("    5. Secret Management 도입 (AWS Secrets Manager / Vault)\n\n")

    # --- 6. 분석 방법론 ---
    out.write("\n" + "━" * 80 + "\n")
    out.write("  6. 분석 방법론\n")
    out.write("━" * 80 + "\n\n")

    out.write("  본 리뷰는 Code Review Pipeline의 4-Agent 시스템으로 수행되었습니다.\n\n")
    out.write("  Agent 1 - Security Agent:\n")
    out.write("    SQL Injection, XSS, 하드코딩된 비밀키, 인증/인가 누락,\n")
    out.write("    로그 인젝션, 안전하지 않은 API 사용 등 보안 취약점 탐지\n\n")
    out.write("  Agent 2 - Performance Agent:\n")
    out.write("    N+1 쿼리, 중첩 루프, 메모리 누수, 블로킹 I/O,\n")
    out.write("    불필요한 직렬 호출, 캐싱 미흡 등 성능 병목 탐지\n")
    out.write("    + Security Agent 결과에 대한 교차 리뷰\n\n")
    out.write("  Agent 3 - Quality Agent:\n")
    out.write("    명명 규칙, 함수 길이, DRY 위반, 타입 힌팅,\n")
    out.write("    에러 처리, 매직 넘버, Dead Code 등 코드 품질 탐지\n")
    out.write("    + Security/Performance Agent 결과에 대한 교차 리뷰\n\n")
    out.write("  Agent 4 - Summary Agent:\n")
    out.write("    중복 제거, 충돌 해소 (Security > Performance > Quality 우선순위),\n")
    out.write("    100점 기준 채점, 등급 부여, Top 3 수정 사항 도출\n\n")

    out.write("  채점 기준:\n")
    out.write("    - Critical 이슈: -15점/건\n")
    out.write("    - Warning 이슈:  -5점/건\n")
    out.write("    - Info 이슈:     -1점/건\n")
    out.write("    - A (90-100), B (80-89), C (70-79), D (60-69), F (0-59)\n\n")

    out.write("=" * 80 + "\n")
    out.write("  END OF REPORT\n")
    out.write("=" * 80 + "\n")

print("Done! Report saved to: output/stock-analyzer_full_review.txt")
