# -*- coding: utf-8 -*-
"""Personal 리뷰 결과 JSON들을 종합하여 output/stock-analyzer_full_review.txt를 생성한다."""

import json
import os
from datetime import date

BATCHES = [
    ("review_personal_batch1.json", "Batch 1: Core (api_client, orchestrator, database, cache, analysis router)"),
    ("review_personal_batch2a.json", "Batch 2a: Agents (analyst, claude_client, cross_validation, compare)"),
    ("review_personal_batch2b.json", "Batch 2b: Agents (news, data, macro, sector_analyzer)"),
    ("review_personal_batch3.json", "Batch 3: Backend Routers (main, quote, sector, compare, market, watchlist, search, alerts, guide)"),
    ("review_personal_batch4a.json", "Batch 4a: Data Clients (finnhub, finviz, fmp, fred)"),
    ("review_personal_batch4b.json", "Batch 4b: Data Clients (twelvedata, yfinance, watchlist, alerts)"),
]

os.makedirs("output", exist_ok=True)

all_data = []
for fname, desc in BATCHES:
    with open(fname, "r", encoding="utf-8") as f:
        data = json.load(f)
    all_data.append((desc, data))

today = date.today().isoformat()

with open("output/stock-analyzer_full_review.txt", "w", encoding="utf-8") as out:
    out.write("=" * 80 + "\n")
    out.write("  STOCK-ANALYZER 전체 코드 리뷰 보고서\n")
    out.write("  Generated by: Code Review Pipeline (4-Agent System)\n")
    out.write(f"  Date: {today}\n")
    out.write("  Level: Personal\n")
    out.write("  Target: stock-analyzer\n")
    out.write("=" * 80 + "\n\n")

    # --- 1. 종합 요약 ---
    out.write("━" * 80 + "\n")
    out.write("  1. 종합 요약 (Executive Summary)\n")
    out.write("━" * 80 + "\n\n")

    total_c, total_w, total_i = 0, 0, 0
    batch_scores = []
    for desc, data in all_data:
        s = data.get("findings", {}).get("summary", {})
        score = s.get("overall_score", 0)
        grade = s.get("grade", "N/A")
        t = s.get("total_issues", {})
        total_c += t.get("critical", 0)
        total_w += t.get("warning", 0)
        total_i += t.get("info", 0)
        batch_scores.append((desc, score, grade, t))

    total_all = total_c + total_w + total_i
    avg_score = sum(s for _, s, _, _ in batch_scores) / len(batch_scores)

    out.write(f"  평균 점수: {avg_score:.0f}/100\n")
    out.write(f"  총 발견 이슈: {total_all}건\n")
    out.write(f"    - Critical: {total_c}건\n")
    out.write(f"    - Warning:  {total_w}건\n")
    out.write(f"    - Info:     {total_i}건\n\n")

    out.write("  분석 대상 파일 (6개 배치, 총 ~3,300줄):\n")
    out.write("    - Core: api_client.py, orchestrator.py, database.py, cache.py, analysis.py\n")
    out.write("    - Agents: analyst, claude_client, cross_validation, compare, news, data, macro, sector\n")
    out.write("    - Backend: main.py + 8개 라우터\n")
    out.write("    - Data Clients: finnhub, finviz, fmp, fred, twelvedata, yfinance, watchlist, alerts\n\n")

    out.write("  배치별 점수:\n")
    out.write("  " + "-" * 76 + "\n")
    out.write(f"  {'배치':<55} {'점수':>8} {'등급':>6}\n")
    out.write("  " + "-" * 76 + "\n")
    for desc, score, grade, t in batch_scores:
        out.write(f"  {desc:<55} {score:>5}/100  {grade:>4}\n")
    out.write("  " + "-" * 76 + "\n\n")

    # --- 2. 배치별 상세 분석 결과 ---
    out.write("\n" + "━" * 80 + "\n")
    out.write("  2. 배치별 상세 분석 결과\n")
    out.write("━" * 80 + "\n")

    for idx, (desc, data) in enumerate(all_data, 1):
        findings = data.get("findings", {})
        summary = findings.get("summary", {})

        out.write(f"\n{'─' * 80}\n")
        out.write(f"  2.{idx} {desc}\n")
        out.write(f"      점수: {summary.get('overall_score', 'N/A')}/100 | 등급: {summary.get('grade', 'N/A')}\n")
        t = summary.get("total_issues", {})
        out.write(f"      이슈: Critical {t.get('critical', 0)} | Warning {t.get('warning', 0)} | Info {t.get('info', 0)}\n")
        out.write(f"{'─' * 80}\n\n")

        for agent_name in ["security", "performance", "quality"]:
            agent_data = findings.get(agent_name, {})
            issues = agent_data.get("issues", [])
            if issues:
                out.write(f"  [{agent_name.capitalize()} Agent 분석 결과]\n\n")
                for i, issue in enumerate(issues, 1):
                    out.write(f"    #{i} [{issue.get('severity', '?').upper()}] (confidence: {issue.get('confidence', '?')})\n")
                    out.write(f"    Line: {issue.get('line', '?')}\n")
                    out.write(f"    이슈: {issue.get('issue', '')}\n")
                    snippet = issue.get("code_snippet", "")
                    if snippet:
                        snippet_display = snippet[:120].replace("\n", " | ")
                        out.write(f"    코드: {snippet_display}\n")
                    suggestion = issue.get("suggestion", "")
                    if suggestion:
                        out.write("    제안:\n")
                        for line in suggestion.split("\n"):
                            out.write(f"      {line}\n")
                    out.write("\n")

                agent_summary = agent_data.get("summary", "")
                if agent_summary:
                    out.write(f"    [{agent_name.capitalize()} 요약]\n")
                    for line in agent_summary.split("\n"):
                        out.write(f"    {line}\n")
                    out.write("\n")

        # cross_review
        for agent_name in ["performance", "quality"]:
            cr = findings.get(agent_name, {}).get("cross_review", [])
            if cr:
                out.write(f"  [{agent_name.capitalize()} 교차 리뷰]\n\n")
                for item in cr:
                    opinion = item.get("opinion", "")
                    out.write(f"    [{opinion.upper()}] {item.get('target_agent', '')} — {item.get('target_issue', '')}\n")
                    out.write(f"    {item.get('comment', '')}\n\n")

    # --- 3. Critical 이슈 통합 ---
    out.write("\n" + "━" * 80 + "\n")
    out.write("  3. Critical 이슈 통합 목록 (즉시 수정 필요)\n")
    out.write("━" * 80 + "\n\n")

    critical_num = 0
    for desc, data in all_data:
        issues = data.get("findings", {}).get("summary", {}).get("all_issues", [])
        for issue in issues:
            if issue.get("severity") == "critical":
                critical_num += 1
                out.write(f"  [{critical_num}] {issue.get('issue', '')}\n")
                out.write(f"      Agent: {issue.get('agent', '?')} | Line: {issue.get('line', '?')}\n")
                out.write(f"      Batch: {desc}\n")
                suggestion = issue.get("suggestion", "")
                first_line = suggestion.split("\n")[0] if suggestion else ""
                out.write(f"      제안: {first_line}\n\n")

    # --- 4. Warning 이슈 통합 ---
    out.write("\n" + "━" * 80 + "\n")
    out.write("  4. Warning 이슈 통합 목록 (개선 권장)\n")
    out.write("━" * 80 + "\n\n")

    warn_num = 0
    for desc, data in all_data:
        issues = data.get("findings", {}).get("summary", {}).get("all_issues", [])
        for issue in issues:
            if issue.get("severity") == "warning":
                warn_num += 1
                out.write(f"  [{warn_num}] {issue.get('issue', '')}\n")
                out.write(f"      Agent: {issue.get('agent', '?')} | Line: {issue.get('line', '?')}\n")
                out.write(f"      Batch: {desc}\n")
                suggestion = issue.get("suggestion", "")
                first_line = suggestion.split("\n")[0] if suggestion else ""
                out.write(f"      제안: {first_line}\n\n")

    # --- 5. 분석 방법론 ---
    out.write("\n" + "━" * 80 + "\n")
    out.write("  5. 분석 방법론\n")
    out.write("━" * 80 + "\n\n")

    out.write("  본 리뷰는 Code Review Pipeline의 4-Agent 시스템으로 수행되었습니다.\n")
    out.write("  프로젝트 레벨: Personal (개인/학습 프로젝트 — 인증 등 인프라 이슈 완화)\n\n")
    out.write("  Agent 1 - Security Agent: 보안 취약점 탐지\n")
    out.write("  Agent 2 - Performance Agent: 성능 병목 탐지 + Security 교차 리뷰\n")
    out.write("  Agent 3 - Quality Agent: 코드 품질 탐지 + Security/Performance 교차 리뷰\n")
    out.write("  Agent 4 - Summary Agent: 중복 제거, 충돌 해소, 채점\n\n")
    out.write("  채점: Critical -15점, Warning -3점, Info -0점\n")
    out.write("  등급: A(90+), B(80+), C(70+), D(60+), F(<60)\n\n")

    out.write("=" * 80 + "\n")
    out.write("  END OF REPORT\n")
    out.write("=" * 80 + "\n")

print(f"Done! avg={avg_score:.0f}, C={total_c}, W={total_w}, I={total_i}")
print("Report saved to: output/stock-analyzer_full_review.txt")
